## Problem 1: Write a program to reverse an array or string

In [2]:
import numpy as np

In [41]:
a = np.array([14, 15 , 78, 85, 54, 63, 13.99])

In [13]:
a

array([14, 15, 78, 85, 54, 63, 25])

In [16]:
def reverse_array(ar):
    rev_ar = ar[::-1]
    return rev_ar

In [17]:
reverse_array(a)

array([25, 63, 54, 85, 78, 15, 14])

## Problem 2: Maximum and minimum of an array using minimum number of comparisons

In [22]:
def min_max(ar):
    temp_max = 0
    temp_min = sum(ar)
    for i in range(len(ar)):
        if ar[i]>temp_max:
            temp_max=ar[i]
        if a[i]<temp_min:
            temp_min=ar[i]
    return temp_max, temp_min

In [40]:
 min_max(a)

(14, 14)

## Problem 3: Find the "Kth" max and min element of an array 

In [55]:
def kth_max(ar, k):
    temp=0
    for i in range(len(ar)):
        for j in range(i,len(ar)):
            if ar[i]>ar[j]:
                temp = ar[i]
                ar[i] = a[j]
                ar[j] = temp
    return ar, ar[k-1], ar[-k]

In [56]:
kth_max(a,3)

(array([13.99, 14.  , 15.  , 54.  , 63.  , 78.  , 85.  ]), 15.0, 63.0)

## Problem 4: Move all negative numbers to beginning and positive to end with constant extra space

In [60]:
def moving_neg_numbers(ar):
    neg = []
    for i in range(len(ar)):
        if ar[i]<0:
            neg.apend(a[i])
    sub_ar = ar - neg
    return [neg, sub_ar]
            
            

In [61]:
moving_neg_numbers([1, -3, -6, 8, 6, -12, 45, -60, 0, 7])

AttributeError: 'list' object has no attribute 'apend'

In [66]:
a.append(23)

AttributeError: 'numpy.ndarray' object has no attribute 'append'